config/routes.rb
Rails.application.routes.draw do
  root 'searches#new'

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  resources :users, only: [:show, :edit, :update]
  resources :trains, only: [:show]
  resources :routes, only: [:index, :show]
  resources :tickets, only: [:index, :new, :show, :create, :destroy]
  resources :carriages, only: [:show]
  resources :railway_stations, only: [:show]

  namespace :admin do
    resources :users
    resources :routes do
      put 'update_name' => 'routes#update_name'
    end
    resources :tickets

    resources :trains do
      resources :carriages, shallow: true
      put 'update_name' => 'trains#update_name'
    end

    resources :railway_stations do
      member do
        patch :update_position
        patch :update_arrival_datetime
        patch :update_departure_datetime
      end
    end
  end

  resource :search do
    get '/' => 'searches#new'
    post '/' => 'searches#show_results'
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  belongs_to :departure_station, class_name: 'RailwayStation'
  belongs_to :arrival_station, class_name: 'RailwayStation'

  after_create :send_ticket_bought_notification
  after_destroy :send_ticket_canceled_notification

  private

  def send_ticket_bought_notification
    TicketsMailer.ticket_bought_notification(self.user, self).deliver_now
  end

  def send_ticket_canceled_notification
    TicketsMailer.ticket_canceled_notification(self.user, self).deliver_now
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [:show, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_url, notice: t('.success_notice')
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket_and_check_its_owner, only: [:show, :destroy]

  def index
    @tickets = current_user.tickets
  end

  def show
  end

  def create
    @ticket = Ticket.new(train_id: params[:train_id], departure_station_id: params[:departure_station_id], arrival_station_id: params[:arrival_station_id])

    current_user.tickets << @ticket

    redirect_to @ticket, notice: t('.success_notice')
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: t('.success_notice')
  end

  private

  def set_ticket_and_check_its_owner
    @ticket = current_user.tickets.find(params[:id])
    redirect_to root_path, alert: 'Доступ запрещён!' unless @ticket.user == current_user
  end
end

app/views/admin/tickets/_ticket_as_table_row.html.erb
<tr>
  <td><%= link_to ticket.train.number, admin_train_path(ticket.train) %></td>
  <td>
    <%= link_to ticket.departure_station.name, admin_railway_station_path(ticket.departure_station) %>
    <br/>
    <%= ticket.train.route.station_in_route(ticket.departure_station.id).arrival_datetime.strftime('%d.%m.%Y %H:%M') %>
  </td>
  <td>
    <%= link_to ticket.arrival_station.name, admin_railway_station_path(ticket.arrival_station) %>
    <br/>
    <%= ticket.train.route.station_in_route(ticket.arrival_station.id).arrival_datetime.strftime('%d.%m.%Y %H:%M') %>
  </td>
</tr>

app/views/admin/tickets/_ticket_as_table_row_full.html.erb
<tr>
  <td><%= link_to ticket.user.full_name, admin_user_path(ticket.user) %></td>
  <td><%= link_to ticket.train.number, admin_train_path(ticket.train) %></td>
  <td>
    <%= link_to ticket.departure_station.name, admin_railway_station_path(ticket.departure_station) %>
    <br/>
    <%= ticket.train.route.station_in_route(ticket.departure_station.id).arrival_datetime.strftime('%d.%m.%Y %H:%M') %>
  </td>
  <td>
    <%= link_to ticket.arrival_station.name, admin_railway_station_path(ticket.arrival_station) %>
    <br/>
    <%= ticket.train.route.station_in_route(ticket.arrival_station.id).arrival_datetime.strftime('%d.%m.%Y %H:%M') %>
  </td>
  <td class="admin-tickets-index-table_controls">
    <%= link_to admin_ticket_path(ticket) do
      bs_icon 'eye-open', tooltip: t('common.show')
    end %>
    <%= link_to admin_ticket_path(ticket), method: :delete, data: { confirm: t('common.are_you_sure') } do
      bs_icon :remove, tooltip: t('common.destroy')
    end %>
  </td>
</tr>

app/views/admin/tickets/index.html.erb
<% @page_title = t '.title' %>

<div class="admin-tickets-index">
  <% if @tickets.present? %>
      <table class="admin-tickets-index-table">
        <thead>
        <tr>
          <th><%= Ticket.human_attribute_name(:user_id) %></th>
          <th><%= Ticket.human_attribute_name(:train_id) %></th>
          <th><%= Ticket.human_attribute_name(:departure_station_id) %></th>
          <th><%= Ticket.human_attribute_name(:arrival_station_id) %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%= render partial: 'admin/tickets/ticket_as_table_row_full', collection: @tickets, as: :ticket %>
        </tbody>
      </table>
  <% else %>
      <h3><%= t '.no_tickets' %></h3>
  <% end %>
</div>

app/views/admin/tickets/show.html.erb
<% @page_title = t '.title', ticket_id: @ticket.id %>

<div class="admin-ticket-show">
  <p>
    <strong><%= Ticket.human_attribute_name(:user_id) %>:</strong>
    <%= link_to @ticket.user.full_name, admin_user_path(@ticket.user) %>
  </p>

  <p>
    <strong><%= Ticket.human_attribute_name(:train_id) %>:</strong>
    <%= link_to @ticket.train.number, train_path(@ticket.train) %>
  </p>

  <p>
    <strong><%= Ticket.human_attribute_name(:departure_station_id) %>:</strong>
    <%= @ticket.departure_station.name %>
    <br>
    <strong><%= RailwayStationsRoute.human_attribute_name(:departure_date_and_time) %>:</strong>
    <%= @ticket.train.route.station_in_route(@ticket.departure_station.id).departure_datetime.strftime('%d.%m.%Y %H:%M') %>
  </p>

  <p>
    <strong><%= Ticket.human_attribute_name(:arrival_station_id) %>:</strong>
    <%= @ticket.arrival_station.name %>
    <br>
    <strong><%= RailwayStationsRoute.human_attribute_name(:arrival_date_and_time) %>:</strong>
    <%= @ticket.train.route.station_in_route(@ticket.arrival_station.id).arrival_datetime.strftime('%d.%m.%Y %H:%M') %>
  </p>

  <div class="admin-ticket-show_actions">
    <%= link_to t('common.return_to_user'), admin_user_path(@ticket.user), class: 'admin-ticket-show_back-button' %>
  </div>
</div>