config/routes.rb
Rails.application.routes.draw do
  root 'searches#new'

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  resources :users, only: [:show, :edit, :update]
  resources :trains, only: [:show]
  resources :routes, only: [:index, :show]
  resources :tickets, only: [:index, :new, :show, :create, :destroy]
  resources :carriages, only: [:show]
  resources :railway_stations, only: [:show]

  namespace :admin do
    resources :users
    resources :routes do
      put 'update_name' => 'routes#update_name'
    end
    resources :tickets

    resources :trains do
      resources :carriages, shallow: true
      put 'update_name' => 'trains#update_name'
    end

    resources :railway_stations do
      member do
        patch :update_position
        patch :update_arrival_datetime
        patch :update_departure_datetime
      end
    end
  end

  resource :search do
    get '/' => 'searches#new'
    post '/' => 'searches#show_results'
  end
end

app/models/search.rb
class Search
  include ActiveModel::Model

  attr_accessor :departure_station_id, :arrival_station_id, :result

  validate :departure_and_arrival_station_must_not_be_same

  def make_search
    routes_with_departure_station = RailwayStation.find(departure_station_id).routes.to_a
    routes_with_arrival_station = RailwayStation.find(arrival_station_id).routes.to_a

    routes_with_both_stations = routes_with_departure_station & routes_with_arrival_station

    routes_with_both_stations.inject([]) do |trains, route|
      departure_station_in_route = route.station_in_route(departure_station_id)
      arrive_station_in_route = route.station_in_route(arrival_station_id)

      if departure_station_in_route.departure_datetime.present? && arrive_station_in_route.arrival_datetime.present?
        route.trains.each do |train|
          trains << train
        end
      end

      trains
    end
  end

  private

  def departure_and_arrival_station_must_not_be_same
    if departure_station_id == arrival_station_id
      errors.add(:base, 'Начальная и конечная станции должны различаться!')
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def show_results
    @search = Search.new(search_params)

    @search.result = @search.make_search if @search.valid?
  end

  private

  def search_params
    params.require(:search).permit(:departure_station_id, :arrival_station_id)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if RailwayStation.count > 1 %>
    <%= form_for @search, method: :post, url: search_path, class: 'search-form' do |f| %>
        <fieldset class="search-form_fields-wrapper">
          <div class="search-form_select-label-wrapper">
            <%= f.label :departure_station_id, 'От', class: 'search-form_select-label' %>
            <div class="search-form_select-wrapper">
              <%= f.select :departure_station_id,
                  RailwayStation.select(:id, :name).all.map { |station| [station.name, station.id] },
                  {},
                  class: 'search-form_select'
              %>
            </div>
          </div>
          <div class="search-form_select-label-wrapper">
            <%= f.label :arrival_station_id, 'До', class: 'search-form_select-label' %>
            <div class="search-form_select-wrapper">
              <%= f.select :arrival_station_id,
                  RailwayStation.select(:id, :name).all.map { |station| [station.name, station.id] },
                  {},
                  class: 'search-form_select'
              %>
            </div>
          </div>
          <div class="search-form_submit-button-wrapper">
            <%= f.submit t('common.make_search'), class: 'search-form_submit-button' %>
          </div>
        </fieldset>
    <% end %>
<% else %>
    <h4><%= t '.unavailable' %></h4>
<% end %>

app/views/searches/_result_item.html.erb
<tr>
  <td><%= link_to train.id, train_path(train), target: '_blank' %></td>
  <td><%= link_to train.route.name, route_path(train.route), target: '_blank' %></td>
  <td><%= train.route.station_in_route(departure_station_id).departure_datetime.strftime('%d.%m.%Y %H:%M') %></td>
  <td><%= train.route.station_in_route(arrival_station_id).arrival_datetime.strftime('%d.%m.%Y %H:%M') %></td>
  <td>
    <% if current_user %>
        <%= form_tag tickets_path do %>
            <%= hidden_field_tag :train_id, train.id %>
            <%= hidden_field_tag :departure_station_id, departure_station_id %>
            <%= hidden_field_tag :arrival_station_id, arrival_station_id %>
            <%= button_tag t('.buy'), class: 'search-result-table_buy-button' %>
        <% end %>
    <% end %>
  </td>
</tr>

app/views/searches/new.html.erb
<% @page_title = t '.title' %>

<%= render 'form' %>

app/views/searches/show_results.html.erb
<% @page_title = "Поиск поездов по маршруту \"#{station_name_by_id(@search.departure_station_id)} – #{station_name_by_id(@search.arrival_station_id)}\"" %>

<% if @search.errors.any? %>
    <% content_for :sidebar do %>
        <%= render 'common/errors', resource: @search %>
    <% end %>
<% end %>

<%= render 'form' %>

<div class="search-result">
  <% if @search.result.present? %>
      <table class="search-result-table">
        <thead>
        <th><%= t '.train' %></th>
        <th><%= t '.route' %></th>
        <th><%= t '.departure_datetime', station_name: station_name_by_id(@search.departure_station_id) %></th>
        <th><%= t '.arrival_datetime', station_name: station_name_by_id(@search.arrival_station_id) %></th>
        <th></th>
        </thead>
        <tbody>
        <%= render partial: 'result_item', collection: @search.result, as: :train,
            locals: {
                departure_station_id: @search.departure_station_id,
                arrival_station_id: @search.arrival_station_id
            } %>
        </tbody>
      </table>
  <% else %>
      <p><%= t '.no_results' %></p>
  <% end %>
</div>