config/routes.rb
Rails.application.routes.draw do
  root 'searches#new'

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  resources :users, only: [:show, :edit, :update]
  resources :trains, only: [:show]
  resources :routes, only: [:index, :show]
  resources :tickets, only: [:index, :new, :show, :create, :destroy]
  resources :carriages, only: [:show]
  resources :railway_stations, only: [:show]

  namespace :admin do
    resources :users
    resources :routes do
      put 'update_name' => 'routes#update_name'
    end
    resources :tickets

    resources :trains do
      resources :carriages, shallow: true
      put 'update_name' => 'trains#update_name'
    end

    resources :railway_stations do
      member do
        patch :update_position
        patch :update_arrival_datetime
        patch :update_departure_datetime
      end
    end
  end

  resource :search do
    get '/' => 'searches#new'
    post '/' => 'searches#show_results'
  end
end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation'
  has_many :tickets, dependent: :destroy
  has_many :carriages, dependent: :nullify

  validates :number, presence: true

  def count_seats(carriage_type, seats_type)
    raise ArgumentError unless Carriage::TYPES.include? carriage_type
    raise ArgumentError unless carriage_type::SEATS_TYPES_ATTRIBUTES_NAMES.include? seats_type

    carriages.where(type: carriage_type).sum(seats_type)
  end

  def update_carriages_positions
    carriages.ordered_by_position.each_with_index do |carriage, index|
      carriage.update_attribute(:position, index + 1)
    end
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to admin_train_path(@train), notice: t('.success_notice')
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_train_path(@train), notice: t('.success_notice')
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_url, notice: t('.success_notice')
  end

  def update_name
    train = Train.find(params[:id])

    train.number = ActionController::Base.helpers.sanitize(params[:name].squish)

    respond_to do |format|
      if train.save
        format.json { render nothing: true, status: :ok}
      else
        format.json { render json: train.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :route_id, :position_from_head)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def show
    @train = Train.find(params[:id])
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<% content_for :sidebar do %>
    <% if @train.errors.any? %>
        <%= render 'common/errors', resource: @train %>
    <% end %>
<% end %>

<%= form_for [:admin, @train], class: 'admin-train-form' do |f| %>
    <div class="admin-train-form_input-row">
      <%= f.label :number %>
      <%= f.text_field :number, class: 'admin-train-form_input' %>
    </div>

    <div class="admin-train-form_checkbox-wrapper">
      <%= f.label :position_from_head do %>
          <%= f.check_box :position_from_head %>
          <%= Train.human_attribute_name(:position_from_head) %>
      <% end %>
    </div>

    <div class="admin-train-form_input-row">
      <%= f.label :route_id %>
      <%= f.collection_select :route_id, Route.select(:id, :name).all, :id, :name, { include_blank: t('.no_route') }, class: 'admin-train-form_input' %>
    </div>

    <div class="actions">
      <%= f.submit t('common.submit'), class: 'admin-train-form_submit-button' %>
    </div>
<% end %>

app/views/admin/trains/_form_name_only.html.erb
<span
  class="js-admin-trains-index-train-number js-admin-trains-index-train-number-<%= train.id %> admin-trains-index-train-number -edit-off"
  contenteditable="false"
  data-toggle="popover"
  data-original-title="<%= t '.edit_name' %>"
  data-model-name="train"
  title="<%= t '.popover_title' %>"
  data-model-id="<%= train.id %>">
  <%= train.number %>
</span>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <%= render partial: 'form_name_only', locals: { train: train } %>
  </td>
  <td class="admin-train-index-table_controls">
    <%= link_to admin_train_path(train) do
      bs_icon 'eye-open', tooltip: t('common.show')
    end %>
    <%= link_to edit_admin_train_path(train) do
      bs_icon :pencil, tooltip: t('common.edit')
    end %>
    <%= link_to admin_train_path(train), method: :delete, data: { confirm: t('common.are_you_sure') } do
      bs_icon :remove, tooltip: t('common.destroy')
    end %>
  </td>
</tr>

app/views/admin/trains/_train_as_list_item.html.erb
<li><%= link_to train.number, admin_train_path(train) %></li>

app/views/admin/trains/edit.html.erb
<% @page_title = t '.title', train_number: @train.number %>

<div class="admin-train-edit">
  <%= render 'form' %>

  <div class="admin-train-edit_actions">
    <%= link_to t('common.return_to_trains'), admin_trains_path, class: 'admin-train-edit_back-button' %>
    <%= link_to t('common.show'), admin_train_path(@train), class: 'admin-train-edit_show-button' %>
  </div>
</div>

app/views/admin/trains/index.html.erb
<% @page_title = t '.title' %>

<div class="admin-train-index">
  <table class="admin-train-index_table admin-train-index-table">
    <thead>
    <tr>
      <th><%= Train.human_attribute_name(:number) %></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <%= render @trains %>
    </tbody>
  </table>

  <div class="admin-train-index_actions">
    <%= link_to t('.new'), new_admin_train_path, class: 'admin-train-index_new-button' %>
  </div>
</div>

app/views/admin/trains/new.html.erb
<% @page_title = t ('.title') %>

<div class="admin-trains-new">
  <%= render 'form' %>

  <div class="admin-trains-new_actions">
    <%= link_to t('common.return_to_trains'), admin_trains_path, class: 'admin-trains-new_back-button' %>
  </div>
</div>

app/views/admin/trains/show.html.erb
<% @page_title = t '.title', train_number: @train.number %>

<div class="admin-train-show">
  <p>
    <strong><%= Train.human_attribute_name(:route_id) %>:</strong>
    <% if @train.route.present? %>
        <%= link_to @train.route.name, admin_route_path(@train.route) %>
    <% else %>
        <%= t '.no_route' %>
    <% end %>
  </p>

  <% if @train.carriages.present? %>
      <h3><%= t '.carriages' %></h3>
      <table class="admin-train-show_carriages-table">
        <thead>
        <th><%= Carriage.human_attribute_name(:position) %></th>
        <th><%= Carriage.human_attribute_name(:type) %></th>
        </thead>
        <tbody>
        <%= render partial: 'admin/carriages/carriage_as_table_row',
            collection: @train.carriages.ordered_by(@train.position_from_head),
            as: :carriage
        %>
        </tbody>
      </table>
  <% else %>
      <h3><%= t '.no_carriages' %></h3>
  <% end %>

  <p>
    <%= link_to t('.add_carriage'), new_admin_train_carriage_path(@train), class: 'admin-train-show_add-carriage-button' %>
  </p>

  <div class="admin-train-show_actions">
    <%= link_to t('common.return_to_trains'), admin_trains_path, class: 'admin-train-show_back-button' %>
    <%= link_to t('common.edit'), edit_admin_train_path(@train), class: 'admin-train-show_edit-button' %>
  </div>
</div>