config/routes.rb
Rails.application.routes.draw do
  root 'searches#new'

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  resources :users, only: [:show, :edit, :update]
  resources :trains, only: [:show]
  resources :routes, only: [:index, :show]
  resources :tickets, only: [:index, :new, :show, :create, :destroy]
  resources :carriages, only: [:show]
  resources :railway_stations, only: [:show]

  namespace :admin do
    resources :users
    resources :routes do
      put 'update_name' => 'routes#update_name'
    end
    resources :tickets

    resources :trains do
      resources :carriages, shallow: true
      put 'update_name' => 'trains#update_name'
    end

    resources :railway_stations do
      member do
        patch :update_position
        patch :update_arrival_datetime
        patch :update_departure_datetime
      end
    end
  end

  resource :search do
    get '/' => 'searches#new'
    post '/' => 'searches#show_results'
  end
end

app/views/common/_admin_header.html.erb
<header class="header">
  <div class="header_wrapper">
    <nav class="main-menu">
      <ul class="main-menu_wrapper">
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.trains'), admin_trains_path %></li>
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.stations'), admin_railway_stations_path %></li>
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.routes'), admin_routes_path %></li>
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.tickets'), admin_tickets_path %></li>
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.users'), admin_users_path %></li>

        <%= render 'common/login_block' %>
      </ul>
    </nav>
  </div>
</header>

app/views/common/_errors.html.erb
<div class="errors">
  <h4 class="errors_header"><%= t 'common.errors_header' %>:</h4>

  <ul class="errors_list errors-list">
    <% resource.errors.messages.each_value do |field_messages| %>
        <% field_messages.each do |message| %>
          <li class="errors-list_item"><%= message %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/common/_flashes.html.erb
<% if flash.notice.present? %>
    <div class="alert-wrapper">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    </div>
<% end %>

<% if flash.alert.present? %>
    <div class="alert-wrapper">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    </div>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="footer_wrapper">
    <%= raw(t('common.footer_copyright', year: Time.new.year, link_to_thinknetica: link_to('онлайн-школе Thinknetica', 'http://www.thinknetica.com/', target: '_blank'))) %>
  </div>
</footer>

app/views/common/_login_block.html.erb
<% if current_user %>
    <li class="main-menu_item -logout">
      <%= link_to t('common.log_out'), destroy_user_session_path, method: :delete %><br/>

      <% if current_user.admin? %>
          <span class="user-name">Привет, <%= link_to current_user.full_name, admin_user_path(current_user) %></span>
      <% else %>
          <span class="user-name">Привет, <%= link_to current_user.full_name, user_path(current_user) %></span>
      <% end %>
    </li>
<% else %>
    <li class="main-menu_item -login"><%= link_to t('common.log_in'), user_session_path %></li>
<% end %>

app/views/common/_user_header.html.erb
<header class="header">
  <div class="header_wrapper">
    <nav class="main-menu">
      <ul class="main-menu_wrapper">
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.search'), search_path %></li>
        <li class="main-menu_item"><%= link_to_unless_current t('common.nav.my_tickets'), tickets_path %></li>
        <%= render 'common/login_block' %>
      </ul>
    </nav>
  </div>
</header>